<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quote;

class QuoteSeeder extends Seeder
{
    public function run()
    {
        $quotes = [
            ['quote' => 'Pendidikan adalah senjata paling ampuh untuk mengubah dunia.', 'author' => 'Nelson Mandela'],
            ['quote' => 'Belajar tanpa berpikir itu sia-sia, berpikir tanpa belajar itu berbahaya.', 'author' => 'Konfusius'],
            ['quote' => 'Investasi terbaik adalah investasi ilmu pengetahuan.', 'author' => 'Benjamin Franklin'],
            ['quote' => 'Masa depan milik mereka yang percaya pada keindahan mimpi-mimpinya.', 'author' => 'Eleanor Roosevelt'],
            ['quote' => 'Satu-satunya cara untuk melakukan pekerjaan hebat adalah mencintai apa yang kamu lakukan.', 'author' => 'Steve Jobs'],
            ['quote' => 'Kesuksesan adalah guru yang buruk. Ia membuat orang pintar berpikir bahwa mereka tidak bisa gagal.', 'author' => 'Bill Gates'],
            ['quote' => 'Jangan pernah berhenti belajar, karena hidup tidak pernah berhenti mengajar.', 'author' => 'Anonim'],
            ['quote' => 'Ilmu itu lebih baik daripada harta. Ilmu menjaga engkau dan engkau menjaga harta.', 'author' => 'Ali bin Abi Thalib'],
            ['quote' => 'Orang yang berhenti belajar akan menjadi pemilik masa lalu. Orang yang terus belajar akan menjadi pemilik masa depan.', 'author' => 'Mario Teguh'],
            ['quote' => 'Pendidikan bukan persiapan untuk hidup, pendidikan adalah hidup itu sendiri.', 'author' => 'John Dewey'],
            ['quote' => 'Kegagalan adalah kesempatan untuk memulai lagi dengan lebih cerdas.', 'author' => 'Henry Ford'],
            ['quote' => 'Setiap ahli pernah menjadi pemula.', 'author' => 'Helen Hayes'],
            ['quote' => 'Disiplin adalah jembatan antara tujuan dan pencapaian.', 'author' => 'Jim Rohn'],
            ['quote' => 'Waktu terbaik untuk menanam pohon adalah 20 tahun lalu. Waktu terbaik kedua adalah sekarang.', 'author' => 'Pepatah Tiongkok'],
            ['quote' => 'Jangan takut gagal, takutlah untuk tidak mencoba.', 'author' => 'Anonim'],
            ['quote' => 'Keberhasilan adalah kemampuan untuk pergi dari satu kegagalan ke kegagalan lain tanpa kehilangan semangat.', 'author' => 'Winston Churchill'],
            ['quote' => 'Bukan tentang seberapa keras kamu terjatuh, tapi seberapa cepat kamu bangkit.', 'author' => 'Anonim'],
            ['quote' => 'Ilmu pengetahuan tanpa agama adalah lumpuh, agama tanpa ilmu pengetahuan adalah buta.', 'author' => 'Albert Einstein'],
            ['quote' => 'Jadilah perubahan yang ingin kamu lihat di dunia.', 'author' => 'Mahatma Gandhi'],
            ['quote' => 'Semakin banyak kamu membaca, semakin banyak hal yang kamu tahu. Semakin banyak yang kamu pelajari, semakin banyak tempat yang bisa kamu tuju.', 'author' => 'Dr. Seuss'],
            ['quote' => 'Pendidikan adalah tiket ke masa depan. Hari esok milik mereka yang mempersiapkannya hari ini.', 'author' => 'Malcolm X'],
            ['quote' => 'Konsistensi adalah kunci keberhasilan.', 'author' => 'Anonim'],
            ['quote' => 'Mimpi besar dimulai dari langkah kecil.', 'author' => 'Anonim'],
            ['quote' => 'Jangan menunggu kesempatan, ciptakanlah.', 'author' => 'George Bernard Shaw'],
            ['quote' => 'Kehadiran adalah langkah pertama menuju kesuksesan.', 'author' => 'Woody Allen'],
            ['quote' => 'Setiap hari adalah kesempatan baru untuk menjadi lebih baik.', 'author' => 'Anonim'],
            ['quote' => 'Kerja keras mengalahkan bakat ketika bakat tidak bekerja keras.', 'author' => 'Tim Notke'],
            ['quote' => 'Jangan biarkan apa yang tidak bisa kamu lakukan menghalangi apa yang bisa kamu lakukan.', 'author' => 'John Wooden'],
            ['quote' => 'Perjalanan seribu mil dimulai dari satu langkah.', 'author' => 'Lao Tzu'],
            ['quote' => 'Sukses bukanlah kunci kebahagiaan. Kebahagiaan adalah kunci kesuksesan.', 'author' => 'Albert Schweitzer'],
            ['quote' => 'Belajar dari kemarin, hidup untuk hari ini, berharap untuk besok.', 'author' => 'Albert Einstein'],
            ['quote' => 'Orang hebat bukan yang tidak pernah jatuh, tapi yang selalu bangkit setelah jatuh.', 'author' => 'Konfusius'],
            ['quote' => 'Pendidikan adalah paspor untuk masa depan.', 'author' => 'Malcolm X'],
            ['quote' => 'Jika kamu tidak bisa terbang, berlarilah. Jika tidak bisa berlari, berjalanlah.', 'author' => 'Martin Luther King Jr.'],
            ['quote' => 'Kamu tidak harus hebat untuk memulai, tapi kamu harus memulai untuk menjadi hebat.', 'author' => 'Zig Ziglar'],
            ['quote' => 'Kesabaran adalah kunci dari segala keberhasilan.', 'author' => 'Anonim'],
            ['quote' => 'Ilmu tanpa amal bagaikan pohon tanpa buah.', 'author' => 'Pepatah Arab'],
            ['quote' => 'Hidup ini seperti naik sepeda. Untuk menjaga keseimbangan, kamu harus terus bergerak.', 'author' => 'Albert Einstein'],
            ['quote' => 'Jangan pernah menyerah pada sesuatu yang tidak bisa kamu lewati sehari tanpa memikirkannya.', 'author' => 'Winston Churchill'],
            ['quote' => 'Keberanian bukan berarti tidak takut, tapi bertindak meskipun takut.', 'author' => 'Mark Twain'],
            ['quote' => 'Setiap pencapaian besar dimulai dari keputusan untuk mencoba.', 'author' => 'Anonim'],
            ['quote' => 'Guru yang biasa-biasa saja memberitahu. Guru yang baik menjelaskan. Guru yang hebat menginspirasi.', 'author' => 'William Arthur Ward'],
            ['quote' => 'Jangan ukur dirimu dengan apa yang telah kamu capai, tapi dengan apa yang seharusnya kamu capai dengan kemampuanmu.', 'author' => 'John Wooden'],
            ['quote' => 'Kegagalan hanyalah kesempatan untuk memulai lagi, kali ini dengan lebih bijaksana.', 'author' => 'Henry Ford'],
            ['quote' => 'Orang yang tidak pernah membuat kesalahan adalah orang yang tidak pernah mencoba sesuatu yang baru.', 'author' => 'Albert Einstein'],
            ['quote' => 'Semangat pagi! Hari ini adalah hari terbaik untuk belajar sesuatu yang baru.', 'author' => 'Anonim'],
            ['quote' => 'Kehadiranmu hari ini adalah investasi untuk masa depanmu.', 'author' => 'Anonim'],
            ['quote' => 'Tetap semangat! Setiap langkah kecil membawamu lebih dekat ke tujuan besar.', 'author' => 'Anonim'],
            ['quote' => 'Jangan bandingkan dirimu dengan orang lain. Bandingkan dirimu dengan dirimu kemarin.', 'author' => 'Jordan Peterson'],
            ['quote' => 'Pengetahuan adalah kekuatan.', 'author' => 'Francis Bacon'],
            ['quote' => 'Satu buku yang bagus bisa mengubah hidupmu selamanya.', 'author' => 'Anonim'],
            ['quote' => 'Jangan pernah berhenti bermimpi, karena mimpi adalah awal dari segala pencapaian.', 'author' => 'Anonim'],
            ['quote' => 'Kamu lebih berani dari yang kamu percaya, lebih kuat dari yang kamu kira.', 'author' => 'A.A. Milne'],
            ['quote' => 'Hari ini sulit, besok akan lebih sulit, tapi lusa akan indah.', 'author' => 'Jack Ma'],
            ['quote' => 'Belajar adalah harta yang akan mengikuti pemiliknya ke mana pun.', 'author' => 'Pepatah Tiongkok'],
            ['quote' => 'Jangan mengeluh tentang apa yang tidak kamu miliki. Gunakan apa yang kamu punya.', 'author' => 'Anonim'],
            ['quote' => 'Setiap orang adalah guru, dan setiap tempat adalah sekolah.', 'author' => 'Ki Hajar Dewantara'],
            ['quote' => 'Ing ngarso sung tulodo, ing madyo mangun karso, tut wuri handayani.', 'author' => 'Ki Hajar Dewantara'],
            ['quote' => 'Keberhasilan tidak diukur dari posisi yang dicapai, tapi dari hambatan yang berhasil diatasi.', 'author' => 'Booker T. Washington'],
            ['quote' => 'Jangan takut untuk tumbuh perlahan, takutlah untuk tidak tumbuh sama sekali.', 'author' => 'Pepatah Tiongkok'],
            ['quote' => 'Orang sukses adalah orang biasa dengan tekad yang luar biasa.', 'author' => 'Anonim'],
            ['quote' => 'Pendidikan mengembangkan kemampuan, bukan menciptakannya.', 'author' => 'Voltaire'],
            ['quote' => 'Satu-satunya batasan untuk pencapaianmu besok adalah keraguan yang kamu miliki hari ini.', 'author' => 'Franklin D. Roosevelt'],
            ['quote' => 'Jangan pernah meremehkan kekuatan konsistensi.', 'author' => 'Anonim'],
            ['quote' => 'Setiap detik yang kamu habiskan untuk belajar adalah detik yang tidak terbuang.', 'author' => 'Anonim'],
            ['quote' => 'Kamu tidak perlu melihat seluruh tangga, cukup ambil langkah pertama.', 'author' => 'Martin Luther King Jr.'],
            ['quote' => 'Keunggulan bukanlah suatu tindakan, melainkan kebiasaan.', 'author' => 'Aristoteles'],
            ['quote' => 'Jangan biarkan sekolah mengganggu pendidikanmu.', 'author' => 'Mark Twain'],
            ['quote' => 'Pikiran yang terbuka adalah awal dari kebijaksanaan.', 'author' => 'Anonim'],
            ['quote' => 'Kamu adalah apa yang kamu lakukan berulang-ulang.', 'author' => 'Aristoteles'],
            ['quote' => 'Jangan menunggu inspirasi, jadilah inspirasi.', 'author' => 'Anonim'],
            ['quote' => 'Setiap master pernah menjadi murid yang gagal.', 'author' => 'Anonim'],
            ['quote' => 'Keberanian untuk memulai adalah setengah dari kemenangan.', 'author' => 'Anonim'],
            ['quote' => 'Ilmu itu cahaya, dan cahaya tidak bisa masuk ke tempat yang tertutup.', 'author' => 'Anonim'],
            ['quote' => 'Hari ini pembaca, besok pemimpin.', 'author' => 'Margaret Fuller'],
            ['quote' => 'Jangan pernah malu untuk bertanya, karena bertanya adalah awal dari pengetahuan.', 'author' => 'Anonim'],
            ['quote' => 'Ketekunan adalah ibu dari keberuntungan.', 'author' => 'Benjamin Franklin'],
            ['quote' => 'Pendidikan bukan mengisi ember, tapi menyalakan api.', 'author' => 'William Butler Yeats'],
            ['quote' => 'Jangan berhenti ketika lelah, berhentilah ketika selesai.', 'author' => 'Anonim'],
            ['quote' => 'Setiap hari yang kamu jalani dengan semangat adalah hari yang bermakna.', 'author' => 'Anonim'],
            ['quote' => 'Kamu tidak bisa mengubah angin, tapi kamu bisa mengatur layar.', 'author' => 'Jimmy Dean'],
            ['quote' => 'Bersyukurlah atas apa yang kamu punya sambil berusaha meraih apa yang kamu inginkan.', 'author' => 'Anonim'],
            ['quote' => 'Waktu yang paling gelap adalah sebelum fajar.', 'author' => 'Pepatah Inggris'],
            ['quote' => 'Jangan pernah meragukan bahwa sekelompok kecil orang yang berkomitmen bisa mengubah dunia.', 'author' => 'Margaret Mead'],
            ['quote' => 'Kebaikan yang kamu lakukan hari ini mungkin dilupakan besok. Tetap berbuat baik.', 'author' => 'Mother Teresa'],
            ['quote' => 'Hidup bukan tentang menemukan dirimu, tapi tentang menciptakan dirimu.', 'author' => 'George Bernard Shaw'],
            ['quote' => 'Satu jam belajar lebih berharga dari satu malam begadang tanpa tujuan.', 'author' => 'Anonim'],
            ['quote' => 'Jadilah mahasiswa yang haus ilmu, bukan yang haus nilai.', 'author' => 'Anonim'],
            ['quote' => 'Kehadiranmu adalah bukti komitmenmu.', 'author' => 'Anonim'],
            ['quote' => 'Setiap pagi membawa harapan baru dan kesempatan baru.', 'author' => 'Anonim'],
            ['quote' => 'Jangan hitung hari, buat setiap hari berarti.', 'author' => 'Muhammad Ali'],
            ['quote' => 'Kamu sudah hebat karena hadir hari ini. Teruslah melangkah!', 'author' => 'Anonim'],
            ['quote' => 'Pendidikan adalah mahkota yang tidak bisa dicuri oleh siapapun.', 'author' => 'Pepatah Afrika'],
            ['quote' => 'Setiap langkah kecil yang konsisten akan membawa perubahan besar.', 'author' => 'Anonim'],
            ['quote' => 'Jangan pernah berhenti bertumbuh, karena itulah tujuan hidup.', 'author' => 'Anonim'],
            ['quote' => 'Kamu tidak perlu sempurna, cukup terus berusaha setiap hari.', 'author' => 'Anonim'],
            ['quote' => 'Ilmu yang bermanfaat adalah ilmu yang diamalkan.', 'author' => 'Pepatah Arab'],
            ['quote' => 'Hari ini adalah hadiah, itulah mengapa disebut present.', 'author' => 'Anonim'],
            ['quote' => 'Keberhasilan dimulai dari keberanian untuk hadir dan mencoba.', 'author' => 'Anonim'],
            ['quote' => 'Jangan pernah meremehkan kekuatan doa dan usaha.', 'author' => 'Anonim'],
        ];

        Quote::truncate();
        foreach ($quotes as $q) {
            Quote::create($q);
        }
    }
}
